name: Auto PR to Main on Push

on:
  push:
    branches-ignore:
      - "main"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: peter-evans/create-pull-request@v6
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Cloud - Update available list
          title: Cloud - Update available list
          body: Cloud - Update available list
          base: main
          labels: automated-pr, Clouds & Regions
          branch: cloud-update-advanced-params
          delete-branch: true

      - name: Pull Request created
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          token: ${{ secrets.TOKEN3 }}
          commit-message: "feat: merge changes from ${{ github.ref }} to main"
          title: "Automated PR to merge ${{ github.ref }} into main"
          body: "This is an automated pull request to update from branch ${{ github.ref }}"
          branch: ${{ steps.create_pr.outputs.branch_name }}-automated-pr-to-main
          base: "main"
          delete-branch: true

      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
