name: Auto PR to Main on Push

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Importante para asegurar que se obtiene toda la historia del repo

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: merge changes from ${{ github.ref }} to main"
          title: "Automated PR to merge ${{ github.ref }} into main"
          body: "This is an automated pull request to update from branch ${{ github.ref }}"
          branch: "automated-pr-${{ github.ref }}-to-main" # Nombre de la rama temporal
          base: "main" # Rama hacia la que se quiere hacer el merge
          delete-branch: true # Opcional: elimina la rama después de hacer merge
