name: Update Branch
on:
  push:
    branches:
      - prueba
jobs:
  updateBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update AUTHORS
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update branch
          title: Update branch
          body: Credit new contributors by updating AUTHORS
          branch: prueba
          base: main
