name: Test Jest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
        with: 
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
